### PR TITLE
Notes for last 8 Surahs (Surah Maoon, Surah Kausar, Surah Kafirun, Surah Nasr, Surah Masad, Surah Ikhals, Surah Falaq and Surah Nas)

### PR DESCRIPTION
**Pull request by mushtaqak**
This PR adds notes for the last 8 surahs of Quran. These include:

- Surah Maoon
- Surah Kausar
- Surah Kafirun
- Surah Nasr
- Surah Masad
- Surah Ikhals
- Surah Falaq
- Surah Nas

### CODE REVIEW

**Comment by mushtaqak** [comment]
@miankhalid This is ready to review and merge.

**Review by miankhalid — CHANGES_REQUESTED** [review]
Nit: The commit message isn't too good imo and it'll be great if we can follow a standard to keep the commit message informative yet have a good looking pattern.

Please have a look at this great article:
http://chris.beams.io/posts/git-commit/

**Comment by mushtaqak** [comment]
@miankhalid updated the commit message

**Review by miankhalid — APPROVED** [review]
Jazak Allah o Khaira!

**Pull request merged**
